### ISSUE TITLE
Projects not loading - Error: Bad Gateway

### ISSUE THREAD

**Issue by louwenjjr** [iomega/paired-data-form#225]
I cannot access the projects: when I go to the list page i get 'Error: Bad Gateway'. 

Link: https://pairedomicsdata.bioinformatics.nl/projects

![image](https://user-images.githubusercontent.com/62542407/156358264-461a8f92-17ba-422f-a349-6ce97314b0c7.png)

**Comment by sverhoeven** [comment]
<details>
<summary>Seems a project in the enrichment queue got replaced which was not caught.</summary>

```
api_1     | /code/dist/store/Memory.js:39
api_1     |             throw new NotFoundException('Not found ' + project_id);
api_1     |                   ^
api_1     |
api_1     | NotFoundException [Error]: Not found b78b5817-86e2-4e5e-a087-a6b0d9710fce.3
api_1     |     at ProjectDocumentMemoryStore.getProject (/code/dist/store/Memory.js:39:19)
api_1     |     at ProjectDocumentStore.<anonymous> (/code/dist/projectdocumentstore.js:67:47)
api_1     |     at Generator.next (<anonymous>)
api_1     |     at /code/dist/projectdocumentstore.js:8:71
api_1     |     at new Promise (<anonymous>)
api_1     |     at __awaiter (/code/dist/projectdocumentstore.js:4:12)
api_1     |     at ProjectDocumentStore.getProject (/code/dist/projectdocumentstore.js:66:16)
api_1     |     at ProjectDocumentStore.<anonymous> (/code/dist/projectdocumentstore.js:47:18)
api_1     |     at Generator.next (<anonymous>)
api_1     |     at /code/dist/projectdocumentstore.js:8:71
```

Restarting it gives
```
api_1     | > podp-api@0.9.4 serve
api_1     | > node --unhandled-rejections=strict dist/server.js
api_1     |
api_1     | undefined:1
api_1     |
api_1     |
api_1     | SyntaxError: Unexpected end of JSON input
api_1     |     at JSON.parse (<anonymous>)
api_1     |     at Object.<anonymous> (/code/dist/util/io.js:20:21)
api_1     |     at Generator.next (<anonymous>)
api_1     |     at fulfilled (/code/dist/util/io.js:5:58)
```
</details>

There was an empty JSON document in the pending folder, that I had to delete so the api service would start again.
